name: subway_arrival_flutter_app
description: Flutter 예제 앱
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
